# After any change to this file you MUST regenerate and checkin
# a .drone.sec even if no secrets were changed. The secrets file is tied
# to a specific .drone.yml so artifacts will not be uploaded to Bintray
# in following builds without an updated .drone.sec
---
branches:
  - ui

clone:
  path: github.com/jooskim/vic
  tags: true

build:
  # build for ui
  # sdk need to be fetched under ui/sdk/
  vicui:
    image: golang:1.6.2
    pull: true
    environment:
      BINTRAY_DOWNLOAD_PATH: "https://bintray.com/vmware/vic-repo/download_file?file_path="
      SDK_PACKAGE_ARCHIVE: "ui-sdk.tar.gz"
      UI_INSTALLER_WIN_UTILS_ARCHIVE: "vic_installation_utils_win.tgz"
      UI_INSTALLER_WIN_PATH: "ui/installer/vCenterForWindows"
      ENV_VSPHERE_SDK_HOME: "/tmp/sdk/vc_sdk_min"
      ENV_FLEX_SDK_HOME: "/tmp/sdk/flex_sdk_min"
    commands:
      - apt-get update
      - apt-get install -yq ant openjdk-7-jdk
      - wget $BINTRAY_DOWNLOAD_PATH$SDK_PACKAGE_ARCHIVE -O /tmp/$SDK_PACKAGE_ARCHIVE
      - wget $BINTRAY_DOWNLOAD_PATH$UI_INSTALLER_WIN_UTILS_ARCHIVE -O /tmp/$UI_INSTALLER_WIN_UTILS_ARCHIVE
      - tar --warning=no-unknown-keyword -xvzf /tmp/$SDK_PACKAGE_ARCHIVE -C /tmp/
      - ant -f ui/vic-ui/build-deployable.xml -Denv.VSPHERE_SDK_HOME=$ENV_VSPHERE_SDK_HOME -Denv.FLEX_HOME=$ENV_FLEX_SDK_HOME
      - tar --warning=no-unknown-keyword -xzvf /tmp/$UI_INSTALLER_WIN_UTILS_ARCHIVE -C $UI_INSTALLER_WIN_PATH

  bundle:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
      BIN_TEMP_DIR: bin/vic
      GOPATH: /drone
      SHELL: /bin/bash
    commands:
      - rm -rf $BIN_TEMP_DIR
      - mkdir -p $BIN_TEMP_DIR
      - cp LICENSE $BIN_TEMP_DIR
      - cp doc/bundle/README $BIN_TEMP_DIR
      # - cp $BIN/vic-machine* $BIN_TEMP_DIR
      # - cp $BIN/appliance.iso $BIN_TEMP_DIR
      # - cp $BIN/bootstrap.iso $BIN_TEMP_DIR
      - mkdir $BIN_TEMP_DIR/ui
      - cp -rf ui/installer/* $BIN_TEMP_DIR/ui
      - sleep 1
      - tar czvf $BIN/vic_$$BUILD_NUMBER.tar.gz -C $BIN vic
      - shasum -a 256 $BIN/vic_$$BUILD_NUMBER.tar.gz
    when:
      success: true
